# Generated by Django 4.2.11 on 2024-05-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='identity',
        ),
    ]
