# Generated by Django 4.2.11 on 2024-05-05 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_education_experience_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='tiktok',
            new_name='github',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='x',
        ),
    ]
