# Generated by Django 4.2.11 on 2024-05-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_rename_tiktok_identity_github_remove_identity_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='born_date',
            field=models.DateField(),
        ),
    ]
