# Generated by Django 4.2.11 on 2024-05-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_alter_education_end_alter_education_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='program',
        ),
        migrations.RemoveField(
            model_name='education',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.CharField(max_length=120),
        ),
    ]
